version: '3'

tasks:
  test:
    desc: 'Run all tests'
    cmds:
      - go test -race -cover ./...
  fmt:
    desc: 'Format codebase'
    cmds:
      - go fmt ./...
  upgrade:
    desc: 'Upgrade dependencies'
    cmds:
      - go get -u -t ./...
